### ISSUE TITLE
BUG vokal pada akhir kata menghilang

### ISSUE THREAD

**Issue by wahyubram82** [WiraDKP/indonesian_syllabelizer#1]
mas wira, luar biasa, tidak pakai database, tapi pakai rumus.
ada bug dikit mas, untuk kata2 yang terakhirnya menggunakan 2 vokal, seperti
bahagia, mesiu, dia, etopia, euforia dll..

hasilnya menjadi
ba-ha-gi, me-si, di, e-to-pi, eu-fo-ri, dst

seperti itulah mas, hilang vokal bagian belakangnya.

mau saya perbaiki belum sempat, soalnya harus pelajari rumus yg mas wira buat dulu, baru bisa koreksi.

**Comment by WiraDKP** [comment]
Terima kasih banyak mas Wahyu. Sudah lama wira tidak sentuh projek ini juga.
Wira coba resolve dulu ya.

**Comment by WiraDKP** [comment]
Terima kasih banyak bug report nya mas Wahyu.
Berikut sudah wira fix ya bug nya. Mohon di pull ke code yang terbaru.

<img width="533" alt="image" src="https://user-images.githubusercontent.com/33952122/82152458-78a24d00-988b-11ea-8c7d-1e5dff611804.png">

Terima kasih dan semoga bisa bermanfaat untuk projek mas Wahyu.

Untuk Indonesia

**Comment by wahyubram82** [comment]
siappp....

Pada tanggal Min, 17 Mei 2020 pukul 22.16 J.COp <notifications@github.com>
menulis:
