### ISSUE TITLE
bug untuk suku kata awal dengan komposisi kkv

### ISSUE THREAD

**Issue by wahyubram82** [WiraDKP/indonesian_syllabelizer#3]
mas wira ada bug lagi...untuk awalan kata, dengan komposisi konsonan-konsonan-vocal (kkv)...
misalnya kata 'drama', 'gratis', dll...akan diubah menjadi 'd-ra-ma' dan 'g-ra'tis'.

saya sudah cek untuk di tengah dan akhir kalimat, tidak terjdi hal tersebut...

misalnya mendramatisir...hasilnya sudah bagus...karena diubah menjadi men-dra-ma-ti-sir
atau pengratisan, diubah menjadi peng-gra-ti-san...

diakhir juga sudah bagus, saya coba, 'hendra', diubah jadi ...'hen-dra'

anehnya, saat saya coba 'nyiur', perubahannya benar...nyi-ur

**Comment by WiraDKP** [comment]
Terima kasih untuk bug reportnya mas @wahyubram82 
Sudah di solve di versi 0.4

<img width="654" alt="image" src="https://user-images.githubusercontent.com/33952122/83949330-562d9f00-a84d-11ea-8e7a-cf97126b34c2.png">

Terima kasih dan semoga bermanfaat.

Untuk Indonesia
